name: workflow_B
on:
  workflow_run:
    workflows: ["workflow_A"]
    branches: ["main"]
    types: [completed]

jobs:
  detect_changes:
    # Only proceed if Workflow A succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout repo at triggering SHA
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Detect changes in folder_1 or folder_2
        id: detect
        shell: bash
        run: |
          sha="${{ github.event.workflow_run.head_sha }}"
          echo "Checking files changed for commit: $sha"

          # List files changed in the (merge) commit. -m handles merge commits.
          git diff-tree -m --no-commit-id --name-only -r "$sha" | tee files.txt

          # Decide changed=true/false
          if grep -E '^(folder_1/|folder_2/)' files.txt >/dev/null 2>&1; then
            changed=true
          else
            changed=false
          fi

          echo "changed=$changed" | tee -a "$GITHUB_OUTPUT"

          echo "----- files.txt -----"
          if [ -s files.txt ]; then cat files.txt; else echo "(empty)"; fi

  job_1:
    needs: detect_changes
    # Run only if detect_changes ran successfully AND either folder changed
    if: ${{ needs.detect_changes.result == 'success' && needs.detect_changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo changed
        run: echo "changed=${{ needs.detect_changes.outputs.changed }}"

      - name: Workflow B
        run: echo "Workflow B ran after workflow A: folder_1 or folder_2 changed."
